/*
 *  This file is part of Tilmac.
 *
 *  Tilmac is free software: you can redistribute it and/or modify
 *  it under the terms of the GNU General Public License as published by
 *  the Free Software Foundation, either version 3 of the License, or
 *  (at your option) any later version.
 * 
 *  Tilmac is distributed in the hope that it will be useful,
 *  but WITHOUT ANY WARRANTY; without even the implied warranty of
 *  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 *  GNU General Public License for more details.
 * 
 *  You should have received a copy of the GNU General Public License
 *  along with Tilmac.  If not, see <http://www.gnu.org/licenses/>.
 */
package com.kayra.tilmac.ui;

import java.sql.SQLException;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JButton;
import static javax.swing.WindowConstants.DISPOSE_ON_CLOSE;
import com.kayra.tilmac.db.DBManager;
import javax.swing.ImageIcon;

/**
 *
 * @author gurhan
 */
public class DictPanel extends javax.swing.JPanel {

    /**
     * Creates new form SozlukPanel
     */
    public DictPanel() {

        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButtonDictOpen = new javax.swing.JButton();
        jButtonDeleteDict = new javax.swing.JButton();

        jButtonDictOpen.setBackground(new java.awt.Color(254, 242, 245));
        jButtonDictOpen.setIcon(new ImageIcon(DictPanel.class.getResource("/icons/book139.png"))); // NOI18N
        jButtonDictOpen.setText("Sözlük 1");
        jButtonDictOpen.setDefaultCapable(false);
        jButtonDictOpen.setFocusTraversalPolicyProvider(true);
        jButtonDictOpen.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButtonDictOpen.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        jButtonDictOpen.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        buttonIsTransparent(jButtonDictOpen, false);
        jButtonDictOpen.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jButtonDictOpenMouseExited(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jButtonDictOpenMouseEntered(evt);
            }
        });
        jButtonDictOpen.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonDictOpenActionPerformed(evt);
            }
        });

        jButtonDeleteDict.setBackground(new java.awt.Color(255, 160, 175));
        jButtonDeleteDict.setIcon(new ImageIcon(DictPanel.class.getResource("/icons/multiplication .png"))); // NOI18N
        jButtonDeleteDict.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jButtonDeleteDictMouseExited(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jButtonDeleteDictMouseEntered(evt);
            }
        });
        jButtonDeleteDict.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonDeleteDictActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButtonDeleteDict, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonDictOpen, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jButtonDictOpen)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButtonDeleteDict)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        buttonIsTransparent(jButtonDeleteDict, false);
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonDictOpenMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButtonDictOpenMouseExited
        buttonIsTransparent(jButtonDictOpen, false);
        buttonIsTransparent(jButtonDeleteDict, false);
        jButtonDictOpen.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/book139.png")));

    }//GEN-LAST:event_jButtonDictOpenMouseExited
    public void setTextJButtonDict(String text) {
        jButtonDictOpen.setText(text);
        jButtonDictOpen.setToolTipText(text);
    }
    private void jButtonDictOpenMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButtonDictOpenMouseEntered
        // TODO add your handling code here:
        buttonIsTransparent(jButtonDictOpen, true);
        buttonIsTransparent(jButtonDeleteDict, true);
        jButtonDictOpen.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/text87.png")));

    }//GEN-LAST:event_jButtonDictOpenMouseEntered

    private void jButtonDictOpenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonDictOpenActionPerformed
        try {
            ArrayList<String> words = DBManager.connector.getWordsinFile(jButtonDictOpen.getText());

            FilesDictForm form = new FilesDictForm();
            form.setTitle(jButtonDictOpen.getText());
            form.setDefaultCloseOperation(DISPOSE_ON_CLOSE);
            form.setWords(words);
            form.setVisible(true);
        } catch (SQLException ex) {
            Logger.getLogger(DictPanel.class.getName()).log(Level.SEVERE, null, ex);
        }

    }//GEN-LAST:event_jButtonDictOpenActionPerformed

    private void jButtonDeleteDictMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButtonDeleteDictMouseExited
        buttonIsTransparent(jButtonDeleteDict, false);
    }//GEN-LAST:event_jButtonDeleteDictMouseExited

    private void jButtonDeleteDictMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButtonDeleteDictMouseEntered
        buttonIsTransparent(jButtonDeleteDict, true);

    }//GEN-LAST:event_jButtonDeleteDictMouseEntered

    private void jButtonDeleteDictActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonDeleteDictActionPerformed

    }//GEN-LAST:event_jButtonDeleteDictActionPerformed

    private void buttonIsTransparent(JButton button, boolean sart) {
        button.setOpaque(sart);
        button.setContentAreaFilled(sart);
        button.setContentAreaFilled(sart);
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JButton jButtonDeleteDict;
    public javax.swing.JButton jButtonDictOpen;
    // End of variables declaration//GEN-END:variables
}
