/*
 *  This file is part of Tilmac.
 *
 *  Tilmac is free software: you can redistribute it and/or modify
 *  it under the terms of the GNU General Public License as published by
 *  the Free Software Foundation, either version 3 of the License, or
 *  (at your option) any later version.
 * 
 *  Tilmac is distributed in the hope that it will be useful,
 *  but WITHOUT ANY WARRANTY; without even the implied warranty of
 *  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 *  GNU General Public License for more details.
 * 
 *  You should have received a copy of the GNU General Public License
 *  along with Tilmac.  If not, see <http://www.gnu.org/licenses/>.
 */
package com.kayra.tilmac.ui;

import java.awt.Dimension;
import java.awt.Toolkit;
import javax.swing.JOptionPane;

/**
 *
 * @author gurhan
 */
public class PageSection extends javax.swing.JDialog {

    /**
     * Creates new form AddPageSection
     */
    public PageSection(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        Dimension screenSize = Toolkit.getDefaultToolkit().getScreenSize();
        int x = (screenSize.width / 2 - this.getWidth() / 2);
        int y = (screenSize.height / 2 - this.getHeight() / 2);
        this.setLocation(x, y);
    }
    private int[][] pages = new int[10][2];
    private int sectionNumber = 0;

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        bindingGroup = new org.jdesktop.beansbinding.BindingGroup();

        jButtonAdd = new javax.swing.JButton();
        jButtonExit = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jSpinnerStart = new javax.swing.JSpinner();
        jLabel1 = new javax.swing.JLabel();
        jSpinnerLast = new javax.swing.JSpinner();
        jLabel2 = new javax.swing.JLabel();
        jCheckBoxOnePage = new javax.swing.JCheckBox();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Sayfa Aralığı Giriniz");
        setType(java.awt.Window.Type.UTILITY);

        jButtonAdd.setText("Tamam");

        org.jdesktop.beansbinding.Binding binding = org.jdesktop.beansbinding.Bindings.createAutoBinding(org.jdesktop.beansbinding.AutoBinding.UpdateStrategy.READ_WRITE, jLabel1, org.jdesktop.beansbinding.ELProperty.create("${font}"), jButtonAdd, org.jdesktop.beansbinding.BeanProperty.create("font"));
        bindingGroup.addBinding(binding);

        jButtonAdd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonAddActionPerformed(evt);
            }
        });

        jButtonExit.setText("İptal");

        binding = org.jdesktop.beansbinding.Bindings.createAutoBinding(org.jdesktop.beansbinding.AutoBinding.UpdateStrategy.READ_WRITE, jLabel1, org.jdesktop.beansbinding.ELProperty.create("${font}"), jButtonExit, org.jdesktop.beansbinding.BeanProperty.create("font"));
        bindingGroup.addBinding(binding);

        jButtonExit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonExitActionPerformed(evt);
            }
        });

        jPanel1.setPreferredSize(new java.awt.Dimension(400, 400));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 64, Short.MAX_VALUE)
        );

        jSpinnerStart.setToolTipText("");

        binding = org.jdesktop.beansbinding.Bindings.createAutoBinding(org.jdesktop.beansbinding.AutoBinding.UpdateStrategy.READ_WRITE, jLabel1, org.jdesktop.beansbinding.ELProperty.create("${font}"), jSpinnerStart, org.jdesktop.beansbinding.BeanProperty.create("font"));
        bindingGroup.addBinding(binding);

        jSpinnerStart.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                jSpinnerStartStateChanged(evt);
            }
        });
        jSpinnerStart.addPropertyChangeListener(new java.beans.PropertyChangeListener() {
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                jSpinnerStartPropertyChange(evt);
            }
        });
        jSpinnerStart.addInputMethodListener(new java.awt.event.InputMethodListener() {
            public void caretPositionChanged(java.awt.event.InputMethodEvent evt) {
            }
            public void inputMethodTextChanged(java.awt.event.InputMethodEvent evt) {
                jSpinnerStartInputMethodTextChanged(evt);
            }
        });
        jSpinnerStart.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jSpinnerStartKeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jSpinnerStartKeyReleased(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Century Schoolbook L", 1, 14)); // NOI18N
        jLabel1.setText("Başlangıç");

        binding = org.jdesktop.beansbinding.Bindings.createAutoBinding(org.jdesktop.beansbinding.AutoBinding.UpdateStrategy.READ_WRITE, jLabel1, org.jdesktop.beansbinding.ELProperty.create("${font}"), jSpinnerLast, org.jdesktop.beansbinding.BeanProperty.create("font"));
        bindingGroup.addBinding(binding);

        jSpinnerLast.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jSpinnerLastMousePressed(evt);
            }
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jSpinnerLastMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jSpinnerLastMouseEntered(evt);
            }
        });
        jSpinnerLast.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                jSpinnerLastStateChanged(evt);
            }
        });

        jLabel2.setText("Bitiş");

        binding = org.jdesktop.beansbinding.Bindings.createAutoBinding(org.jdesktop.beansbinding.AutoBinding.UpdateStrategy.READ_WRITE, jLabel1, org.jdesktop.beansbinding.ELProperty.create("${font}"), jLabel2, org.jdesktop.beansbinding.BeanProperty.create("font"));
        bindingGroup.addBinding(binding);

        jCheckBoxOnePage.setText("Sadece tek sayfa almak istiyorum");

        binding = org.jdesktop.beansbinding.Bindings.createAutoBinding(org.jdesktop.beansbinding.AutoBinding.UpdateStrategy.READ_WRITE, jLabel1, org.jdesktop.beansbinding.ELProperty.create("${font}"), jCheckBoxOnePage, org.jdesktop.beansbinding.BeanProperty.create("font"));
        bindingGroup.addBinding(binding);

        jCheckBoxOnePage.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBoxOnePageActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jSpinnerStart, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel2)
                        .addGap(31, 31, 31)
                        .addComponent(jSpinnerLast, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jCheckBoxOnePage)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 0, Short.MAX_VALUE)
                .addGap(31, 31, 31))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButtonAdd)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButtonExit)
                .addGap(125, 125, 125))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(19, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel1)
                            .addComponent(jSpinnerStart, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jSpinnerLast, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel2))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jCheckBoxOnePage)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonExit)
                    .addComponent(jButtonAdd))
                .addContainerGap())
        );

        jSpinnerStart.setValue(1);
        jSpinnerLast.setValue(2);

        bindingGroup.bind();

        pack();
    }// </editor-fold>//GEN-END:initComponents
    /**
     * Sayfa aralığı alma. Her sayfa aralığı 2 elemanlı bir dizi olarak alınıp
     * daha sonra sayfa aralıkları dizisine eklenir. Mainform da bu iki boyutlu
     * sayfa aralıkları dizisini kullanır. Her ekleme sonunda kullanıcıya 'başka
     * sayfa aralığı eklemek ister misiniz ?' diye sorulur.
     *
     * @param evt
     */
    private void jButtonAddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonAddActionPerformed
        int start;
        int last;
        if (sectionNumber >= 9) {
            JOptionPane.showMessageDialog(this, "Aralık girme hakkınız doldu");
        }
        try {
            start = Integer.parseInt(jSpinnerStart.getValue().toString());
            if (jSpinnerLast.isEnabled()) {
                last = Integer.parseInt(jSpinnerLast.getValue().toString());
            } else {
                last = start;
            }
            if (start > last && start >= 1 && last >= 1) {
                JOptionPane.showMessageDialog(this, "Değerleri Düzgün Girin");
                return;
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Hata oluştu sadece sayı girin");
            return;
        }
        pages[sectionNumber][0] = start;
        pages[sectionNumber][1] = last;
        sectionNumber++;
        String[] answersOfSelection = {"Evet", "Hayır"};
        int selection = JOptionPane.showOptionDialog(this, " Başka bölüm eklemek istiyor musunuz ?", "Başka kısım var mı?", 0, JOptionPane.INFORMATION_MESSAGE, null, answersOfSelection, null);

        if (selection == 0) {
            jSpinnerStart.setValue(last + 1);
            jSpinnerLast.setValue(last + 2);
            return;
        } else if (selection == 1) {
            this.dispose();

        }
    }//GEN-LAST:event_jButtonAddActionPerformed

    private void jButtonExitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonExitActionPerformed
        this.dispose();
        pages[sectionNumber][0] = -1;
        pages[sectionNumber][1] = -1;
        sectionNumber--;
    }//GEN-LAST:event_jButtonExitActionPerformed

    private void jCheckBoxOnePageActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBoxOnePageActionPerformed
        // TODO add your handling code here:
        if (jCheckBoxOnePage.isSelected()) {
            jSpinnerLast.setEnabled(false);
        } else {
            jSpinnerLast.setEnabled(true);
        }
    }//GEN-LAST:event_jCheckBoxOnePageActionPerformed

    private void jSpinnerStartPropertyChange(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_jSpinnerStartPropertyChange
        // TODO add your hand
    }//GEN-LAST:event_jSpinnerStartPropertyChange

    private void jSpinnerStartStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_jSpinnerStartStateChanged
        // TODO add your handling code here:
    }//GEN-LAST:event_jSpinnerStartStateChanged

    private void jSpinnerStartInputMethodTextChanged(java.awt.event.InputMethodEvent evt) {//GEN-FIRST:event_jSpinnerStartInputMethodTextChanged
        // TODO add your handling code here:

    }//GEN-LAST:event_jSpinnerStartInputMethodTextChanged

    private void jSpinnerStartKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jSpinnerStartKeyReleased
        int sayi = (int) jSpinnerStart.getValue();
        System.out.println(sayi);
    }//GEN-LAST:event_jSpinnerStartKeyReleased

    private void jSpinnerStartKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jSpinnerStartKeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_jSpinnerStartKeyPressed

    private void jSpinnerLastStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_jSpinnerLastStateChanged
        // TODO add your handling code here:
    }//GEN-LAST:event_jSpinnerLastStateChanged

    private void jSpinnerLastMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jSpinnerLastMouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_jSpinnerLastMouseEntered

    private void jSpinnerLastMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jSpinnerLastMouseClicked
    }//GEN-LAST:event_jSpinnerLastMouseClicked

    private void jSpinnerLastMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jSpinnerLastMousePressed
        // TODO add your handling code here:
    }//GEN-LAST:event_jSpinnerLastMousePressed

    /**
     * @param args the command line arguments
     */
    public int[][] getPageSection() {
        return this.pages;
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonAdd;
    private javax.swing.JButton jButtonExit;
    private javax.swing.JCheckBox jCheckBoxOnePage;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JSpinner jSpinnerLast;
    private javax.swing.JSpinner jSpinnerStart;
    private org.jdesktop.beansbinding.BindingGroup bindingGroup;
    // End of variables declaration//GEN-END:variables
}
